---
title: "Support for Radical Left Parties"
author: "Blanca & Yasmeen"
date: '2024-11-08'
output: html_document
---
```{r}
library(readr)
library(stargazer)
library(dplyr)

ESS10 <- read_csv("ESS10.csv")
CHES <- read_csv("1999-2019_CHES_dataset_means(v3).csv")
```

Let's select the variables that are important. 

```{r}
ess_selected10 <- ESS10

# Filter out rows that contain 7, 8, 9, 77, 88, or 99 in any column
ess_selected10 <- ess_selected10 |>
  filter(
    !gndr %in% 9,
    !domicil %in% c(7, 8, 9),
    !hinctnta %in% c(77, 88, 99),
    !imsmetn %in% c(7, 8, 9),
    !imdfetn %in% c(7, 8, 9),
    !impcntr %in% c(7, 8, 9),
    !imwbcnt %in% c(77, 88, 99),
    !imbgeco %in% c(77, 88, 99),
    !imueclt %in% c(77, 88, 99),
    !gincdif %in% c(7, 8, 9),
    !euftf %in% c(77, 88, 99),
    !wrclmch %in% c(7, 8, 9),
    !lrscale %in% c(77, 88, 99),
    !trstlgl %in% c(77, 88, 99),
    !trstplc %in% c(77, 88, 99),
    !trstplt %in% c(77, 88, 99),
    !trstprt %in% c(77, 88, 99),
    !trstprl %in% c(77, 88, 99),
    !trstep %in% c(77, 88, 99),
    !trstun %in% c(77, 88, 99),
    !stfgov %in% c(77, 88, 99),
    !viepolc %in% c(77, 88, 99)
  )
  
# calculate support for immigration
ess_selected <- ess_selected |> mutate (
  support_mig = (imsmetn + imdfetn + impcntr) / 3,
  support_mig_recoded = 4 - support_mig # this recodes the variable so 0 is no support and 4 is full support
  )

ess_selected <- ess_selected |> mutate (
    migration_good =  (imwbcnt + imbgeco + imueclt) / 3
  ) # if value is close to 0, migration is considered bad for the country

# checking if it makes sense to keep them separate
correlation_result <- cor(ess_selected$support_mig, ess_selected$migration_good)
print(correlation_result)

# we conclude it does

# climate concern
ess_selected <- ess_selected |> mutate (
    climate =  wrclmch 
    )

# EU integration
ess_selected <- ess_selected |> mutate (
    euint =  euftf
    )

# EU vote
ess_selected <- ess_selected |> mutate (
    euvote = vteurmmb
    )

# trust in politics
ess_selected <- ess_selected |> mutate (
    trustpol =  (trstplt  + trstprt) / 2
    )

# trust in law enforcement
ess_selected <- ess_selected |> mutate (
    trustlaw =  (trstlgl  + trstplc) / 2
    )

# reversing support for redistribution
ess_selected <- ess_selected |> mutate (
    redistribution =  6 - gincdif 
    )

# start coding the dependent variable
ess_selected1 <- ess_selected |>
  mutate(
    party_vote = coalesce(prtvtebe, prtvtebg, prtvthch, prtvtbhr, prtvtecz, 
                          prtvthee, prtvtefi, prtvtefr, prtvtdgr, prtvtghu, 
                          prtvtdis, prtvtdie, prtvtdit, prtvclt1, prtvtame, 
                          prtvthnl, prtvtmk, prtvtbno, prtvtdpt, prtvtfsi, 
                          prtvtesk, prtvtdgb
                          )) |>
  select(-starts_with("prtv")) 

```

Now we recode the CHES to select only radical left parties in the last measurement year (2019).

```{r}
ches_selected <- CHES |> select (country, year, family, party, party_id
                                     )

ches_filtered <- ches_selected |> filter (year %in% 2019)|>
  filter (family %in% 6) 
```

After some desk research, we combine both datasets to code voters of the radical left in the ESS dataset.  

```{r}
ess_selected2 <- ess_selected1 |>
  mutate(
    vote_left = case_when(
      (cntry == "BE" & party_vote == 5) ~ 1,
      (cntry == "CZ" & party_vote == 1) ~ 1,
      (cntry == "FI" & party_vote == 18) ~ 1,
      (cntry == "FR" & party_vote %in% c(3, 4)) ~ 1,
      (cntry == "GR" & party_vote %in% c(2, 4, 6)) ~ 1,
      (cntry == "HU" & party_vote == 8) ~ 1,
      (cntry == "IE" & party_vote %in% c(8, 11)) ~ 1,
      (cntry == "NL" & party_vote == 4) ~ 1,
      (cntry == "PT" & party_vote %in% c(2, 12, 13)) ~ 1,
      TRUE ~ 0  
    )
  )

# filtering for countries who have those parties to begin with (the ones that were both in CHES and ESS)

ess_selected2 <- ess_selected2 |> filter (cntry == c("BE", "CZ", "FI", "FR", "GR", "HU", "IE", "NL", "PT"))

ess_selected2 <- ess_selected2 |>
  select (cntry, gndr, hinctnta, eduyrs, vote_left, support_mig, migration_good, climate, euint, euvote, trustpol, 
          trustlaw, trstprl, trstep, trstun, stfgov, viepolc, lrscale , redistribution , domicil
  )

```
Visualizing the dependent variable

```{r}
library(ggplot2)

plot <- ggplot(ess_selected2, aes(x = cntry, fill = factor(vote_left))) +
  geom_bar(position = "dodge") +
  labs(
    x = "Country",
    y = "Frequency",
    fill = "Vote Left"
    ) +
  theme_minimal()

ggsave("vote_left_by_country.jpeg", plot, width = 8, height = 6)

```


And then we run a model predicting a 1 on vote for the radical left

```{r}

model_logit <- glm(vote_left ~  gndr + hinctnta + eduyrs + support_mig + migration_good +
                     climate + euint + euvote + trustpol + trustlaw + trstprl + trstep + trstun +
                     stfgov + viepolc + lrscale + redistribution + domicil + cntry, data= ess_selected2, 
                   family = binomial)

model_logit_nofe <- glm(vote_left ~  gndr + hinctnta + eduyrs + support_mig + migration_good +
                     climate + euint + euvote + trustpol + trustlaw + trstprl + trstep + trstun +
                     stfgov + viepolc + lrscale + redistribution + domicil, data= ess_selected2, 
                   family = binomial)

model_linear <- lm(vote_left ~ cntry + gndr + hinctnta + eduyrs + support_mig + migration_good +
                     climate + euint + euvote + trustpol + trustlaw + trstep + trstprl + trstun +
                     stfgov + viepolc + lrscale + redistribution + domicil, data= ess_selected2, 
                   family = binomial)

stargazer(model_logit, 
          type = "text",
          omit= "cntry",
          add.lines = list(
            c("Country Fixed Effects", "YES"
              )))

stargazer(model_linear, 
          type = "text",
          omit= "cntry",
          add.lines = list(
            c("Country Fixed Effects", "YES"
              )))


stargazer(model_logit, model_logit_nofe, type= "latex",
          dep.var.labels = "voted for extreme left",
          covariate.labels = c(
            "Gender", 
            "Income", 
            "Education",
            "Support for Migration", 
            "Finds Migration Good", 
            "Concerned about the Climate", 
            "EU Integration", 
            "EU In-Out Vote", 
            "Trust in Politicians", 
            "Trust in the Rule of Law", 
            "Trust in Government", 
            "Trust in EU Parliament", 
            "Trust in the UN", 
            "Satisfaction with Government", 
            "View of Elites", 
            "Left-Right Scale", 
            "Redistribution", 
            "Rural"),
          omit = "cntry",
           omit.stat = c("LL", "ser", "f"),
          add.lines = list(c("Country Fixed Effects", "YES", "NO"),
          notes = "Values are logged-odds",
          notes.align = "l")
          )

```